---
variables:
  DEBIAN_OLDSTABLE_CODE: stretch
  DEBIAN_OLDSTABLE_VERSION: 9
  DEBIAN_OLDSTABLE_FULL: Debian 9 "stretch"
  DEBIAN_STABLE_CODE: buster
  DEBIAN_STABLE_VERSION: 10
  DEBIAN_STABLE_FULL: Debian 10 "buster"
  UBUNTU_OLDLTS_CODE: bionic
  UBUNTU_OLDLTS_VERSION: 1804
  UBUNTU_OLDLTS_FULL: Ubuntu 18.04 "Bionic Beaver"
  MINT_OLDLTS_CODE: tara
  MINT_OLDLTS_VERSION: 19
  MINT_OLDLTS_FULL: Linux Mint 20
  UBUNTU_LTS_CODE: focal
  UBUNTU_LTS_VERSION: 2004
  UBUNTU_LTS_FULL: Ubuntu 20.04 "Focal Fossa"
  MINT_LTS_CODE: ulyana
  MINT_LTS_VERSION: 20
  MINT_LTS_FULL: Linux Mint 20
  #UBUNTU_STABLE_CODE: eoan
  #UBUNTU_STABLE_VERSION: 1910
  #UBUNTU_STABLE_FULL: Ubuntu 19.10 "Eoan Ermine"
  FEDORA_OLDSTABLE_VERSION: 30
  FEDORA_STABLE_VERSION: 31
  CENTOS_OLDSTABLE_VERSION: 7
  CENTOS_STABLE_VERSION: 8
  OPENSUSE_OLDSTABLE_VERSION: "15.0"
  OPENSUSE_STABLE_VERSION: "15.1"
